### ISSUE TITLE
Hide Branch Level 0 without hiding children

### ISSUE THREAD

**Issue by jsale** [openantz/antz#226]
I am hoping this is do-able and relatively easy. It is usually the case that child objects are smaller than parents and can be obscured by them as a result, so it is nice to hide the parent. Unfortunately hiding the root branch level 0 object hides all children as well. My only other option is to set color_a to 0 but transparency is also kind of odd in ANTz and doesn't work the way one might expect.

**Comment by saxondigital** [comment]
Here's a link to a quick hack that allows hiding the root pin while
allowing you to still draw the child nodes.

http://openantz.com/code/msw/antz-msw_2016-06-07.zip

Will put this the next release, and perhaps modify the user hide behavior
so that you can manually hide entire pins, but override the hide at any
branch level.

**Comment by jsale** [comment]
Thanks, Shane! I am giving a demo to my new boss tomorrow and this will
really help.

Jeff
