### ISSUE TITLE
Zoom navigation glitches

### ISSUE THREAD

**Issue by anne-Matri** [openantz/antz#311]
When zooming in/ out with L & R mouse keys, the zoom often fails and doesn't move the scene. I have to click on different objects or change World to Local heading. But it does this often.

**Comment by saxondigital** [comment]
There is a bug in MSW mouse handling, and no known solution is known at this time. It only happens when the secondary R-hold button is pressed while the mouse is moving (and the L-hold is already pressed).

Workaround: The Zoom-Orbit combo will work if the mouse is NOT moving when pressing the secondary R-hold button.

**Comment by saxondigital** [comment]
Bug appears to have been fixed with latest W10 updates (tested on 2022-04-19).
