### ISSUE TITLE
Topo key switches to facet (as if Alt+J is pressed)

### ISSUE THREAD

**Issue by anne-Matri** [openantz/antz#312]
Sometimes the 'J' key doesn't work and only changes facets, not topo's. I can't switch topo's using Alt-J either.

**Comment by saxondigital** [comment]
Best guesses are:
- Sticky 'ALT' key on the keyboard.
- Known issue of changing window contexts while holding the 'ALT' key, where the app does not know the key is released. So that the app believes the 'ALT' key is still pressed, (Alt+J is the command to change facets, so in this case just pressing 'J' would appear as an Alt+J to the app).
  - Changing window contexts happens when you click on another window or hit Alt+Tab.

**Comment by saxondigital** [comment]
Fixed in v0.228.8
